# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: "05 20 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install lxml  # Install lxml library
    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Python Script
      run: python fbref_scraper.py
    - name: Commit CSV File
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add all_leagues_2023_2024.csv
        git commit -m "Add CSV file generated by scraper"
        git push
